### ISSUE TITLE
Compile error on activation (Shopware Version 6.4.7.0)

### ISSUE THREAD

**Issue by derBoogie** [mnaczenski/MNExtendSearch#3]
I'm getting the following error during the activation of the plugin (Shopware 6.4.7.0): 

Compile Error: Declaration of MNExtendSearch\Service\MySearchKeywordAnalyser::analyze(Shopware\Core\Content\Product\ProductEntity $product,
Shopware\Core\Framework\Context $context): Shopware\Core\Content\Product\SearchKeyword\AnalyzedKeywordCollection must be compatible with Shopware\Core\Content\Product\SearchKeyword\ProductSearchKeywordAnalyzerInterface::analyze(Shopware\Core\Content\Product\ProductEntity $product,
Shopware\Core\Framework\Context $context, array $configFields): Shopware\Core\Content\Product\SearchKeyword\AnalyzedKeywordCollection

**Comment by mnaczenski** [comment]
Most of the plugins functionality is part of the core in 6.4.7.0. So it won't get an update to be compatible.
Just use the search configuration in the settings of the admin.

**Comment by derBoogie** [comment]
But the plugin can not be activated.
![Bug-Suche](https://user-images.githubusercontent.com/1611217/151929841-9872a17e-b645-421e-8a80-068002acfa3a.jpg)

**Comment by derBoogie** [comment]
The core changed.
Function analyze in /custom/plugins/MNExtendSearch/src/Service/MySearchKeywordAnalyser.php needs 3 params:

```
public function analyze(ProductEntity $product, Context $context, array $configFields): AnalyzedKeywordCollection
{
  $keywords = $this->coreAnalyzer->analyze($product, $context, $configFields);
...
```

**Comment by mnaczenski** [comment]
Why do you want to use it at all? The functionality of the plugin is already there without the plugin.
So it is obsolete in the current version and you won't need it any more.

**Comment by derBoogie** [comment]
How can the product description be activated without the plugin, for example?
![Suche-Textbeschreibung](https://user-images.githubusercontent.com/1611217/152179706-8635afa7-fa32-4dbb-9a10-9322c0dd29c0.jpg)

**Comment by mnaczenski** [comment]
Just double klick on the row to make it editable.
This is also stated in the corresponding documentation: https://docs.shopware.com/en/shopware-6-en/settings/search#searchable-content

**Comment by derBoogie** [comment]
Hey @mnaczenski 
those who can read are at a clear advantage ;)
Thank's very much for the double klick hint!
